### ISSUE TITLE
Error Creating data mats for train....

### ISSUE THREAD

**Issue by abrar1515** [batra-mlp-lab/visdial-rl#15]
kindly help me error is occur during executing of prepro.py file error is
Traceback (most recent call last):
  File "prepro.py", line 274, in <module>
    captions_train, captions_train_len, questions_train, questions_train_len, answers_train, answers_train_len, options_train, options_train_list, options_train_len, answers_train_index, images_train_index, images_train_list, _ = create_data_mats(data_train_toks, ques_train_inds, ans_train_inds, args, 'train')
  File "prepro.py", line 127, in create_data_mats
    options[i][j] = np.array(data_toks[image_id]['dialog'][j]['answer_options']) + 1
ValueError: could not broadcast input array from shape (104) into shape (100)

**Comment by abrar1515** [comment]
solved with online downloading...
